### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by timandy** [goproxyio/goproxy#198]
@oiooj  Hi, when I update  testify to the latest version, some error occurs.

``` shell
go get github.com/stretchr/testify@v1.7.1
```
output:

github.com/stretchr/testify/assert: github.com/stretchr/testify@v1.7.1: verifying module: github.com/stretchr/testify@v1.7.1: reading https://goproxy.io/sumdb/sum.golang.org/lookup/github.com/stretchr/testify@v1.7.1: stream error: stream ID 5; INTERNAL_ERROR; received from peer

![image](https://user-images.githubusercontent.com/3809541/158566633-1a394545-0d13-44a9-998b-26e468ef8038.png)

**Comment by dhiller** [comment]
We are having similar errors, example here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7374/pull-kubevirt-e2e-k8s-1.23-operator/1504057360094597120

Our CI search reveals that we are getting a lot of the INTERNAL_ERROR s recently (since around 24h, also happened 4days ago): https://search.ci.kubevirt.io/?search=INTERNAL_ERROR&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

A manual curl could reproduce the problem, so we are assuming that there is something wrong with the backend?

```
curl -Lv https://goproxy.io/sumdb/sum.golang.org/lookup/golang.org/x/sys@v0.0.0-20220315194320-039c03cc5b86
*   Trying 119.28.201.50:443...
...
< server: nginx/1.16.1
< date: Wed, 16 Mar 2022 11:46:13 GMT
< content-type: text/plain; charset=utf-8
< content-length: 403
< x-cache-status: MISS
< 
* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
* Connection #0 to host goproxy.io left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**Comment by dhiller** [comment]
One more note: while we are using bazel, we also experienced this to happen in pure go builds.

**Comment by oiooj** [comment]
Fixed Thanks @timandy
